name: data_fixture_dart
description: Creation of data model easily, with no headache.
version: 2.2.0
homepage: https://github.com/andreadelfante/data_fixture_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  faker: ^2.0.0

dev_dependencies:
  test: ^1.20.2
