name: data_fixture_dart
description: Creation of data model easily, with no headache.
version: 3.0.0
repository: https://github.com/MyLittleSuite/data_fixture_dart
issue_tracker: https://github.com/MyLittleSuite/data_fixture_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  faker: ^2.0.0

dev_dependencies:
  test: ^1.20.2
