name: data_fixture_dart
description: Creation of data model easily, with no headache.
version: 1.0.0
homepage: https://github.com/andreadelfante/data_fixture_dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  faker: ">=1.2.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
