enum FakerType {
  personFirstName,
  personLastName,
  personName,
  internetEmail,
  internetUrl,
  dateDateTime,
  loremWord,
  loremSentence,
  randomInt,
  randomDouble,
  addressCity,
  addressCountry,
  phoneNumber,
  companyName,
}
